env:
  rcloneconfig: ENCRYPTED[48a947cbdfde6ae994690178b4de65e5239c083d68609787864eb37fda9c314f90d963c9800761664bc5339cf827fa23]
  
task:
  name: "Blobs extractor"
  timeout_in: 120m
  skip: $CIRRUS_BRANCH == 'main'
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 3
      memory: 12G

  DownloadDumpAndSetup_script:
      - echo "------- THIS CI RUN MEANT TO RUN WITH DUMPRX ------------"
      - echo "------- PLEASE DO DUMP YOUR ROM ON DUMPRX ---------------"
      - git clone --depth=1 "$(cat D*.txt)" ~/Dump/
      - git config --global user.name "adrian-8901"
      - git config --global user.email "adrianlam230@gmail.com"
      - git clone https://github.com/LineageOS/android_tools_extract-utils.git -b lineage-19.1 ~/tools/extract-utils
      
  BlobsExtractor_script:
      - mkdir -p ~/.rclone
      - echo "$rcloneconfig" >> ~/.rclone.conf
      - sudo bash blobs.sh
      
      
      
