env:
  GITHUB_TOKEN: ENCRYPTED[4ad429f31f3747a4635592ef2fe580af170fddc7ece23ccac0b1ac154eb2f812d3786851936aaef1fb0b501d6a150422]
  repo: "umiBlobs"
  GIT_ORG: "BlobsPx"
  
task:
  name: "Blobs extractor"
  timeout_in: 120m
  skip: $CIRRUS_BRANCH == 'main'
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 3
      memory: 12G

  DownloadDumpAndSetup_script:
      - echo "------- THIS CI RUN MEANT TO RUN WITH DUMPRX ------------"
      - echo "------- PLEASE DO DUMP YOUR ROM ON DUMPRX ---------------"
      - git clone --depth=1 "$(cat D*.txt)" ~/Dump/
      - git config --global user.name "adrian-8901"
      - git config --global user.email "adrianlam230@gmail.com"
      - git clone https://github.com/LineageOS/android_tools_extract-utils.git -b lineage-19.1 ~/tools/extract-utils
      
  BlobsExtractor_script:
      - chmod 777 ~/Dump/*
      - bash blobs.sh
      
      
      
